# Generated by Django 2.2 on 2019-09-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=50)),
                ('FileNumber', models.PositiveIntegerField()),
                ('Location', models.CharField(max_length=50)),
                ('Sector', models.CharField(max_length=50)),
                ('Work_Date', models.DateTimeField(auto_now_add=True)),
                ('Time_In', models.DateTimeField(auto_now_add=True)),
                ('Time_Out', models.DateTimeField(auto_now_add=True)),
                ('Hours_Worked', models.DateTimeField(auto_now_add=True)),
                ('Hours_Code', models.CharField(max_length=50)),
                ('Report_Date', models.DateTimeField(auto_now_add=True)),
                ('Batch_ID', models.PositiveIntegerField()),
                ('Company_Code', models.PositiveIntegerField()),
            ],
        ),
    ]
